// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: internal/grpc/proto/config_sync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigSync_Connect_FullMethodName = "/wolink.ConfigSync/Connect"
)

// ConfigSyncClient is the client API for ConfigSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigSync service for bidirectional streaming between admin and gateway nodes
type ConfigSyncClient interface {
	// Connect establishes a bidirectional stream for heartbeats and config updates
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Heartbeat, ConfigUpdate], error)
}

type configSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigSyncClient(cc grpc.ClientConnInterface) ConfigSyncClient {
	return &configSyncClient{cc}
}

func (c *configSyncClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Heartbeat, ConfigUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigSync_ServiceDesc.Streams[0], ConfigSync_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Heartbeat, ConfigUpdate]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigSync_ConnectClient = grpc.BidiStreamingClient[Heartbeat, ConfigUpdate]

// ConfigSyncServer is the server API for ConfigSync service.
// All implementations must embed UnimplementedConfigSyncServer
// for forward compatibility.
//
// ConfigSync service for bidirectional streaming between admin and gateway nodes
type ConfigSyncServer interface {
	// Connect establishes a bidirectional stream for heartbeats and config updates
	Connect(grpc.BidiStreamingServer[Heartbeat, ConfigUpdate]) error
	mustEmbedUnimplementedConfigSyncServer()
}

// UnimplementedConfigSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigSyncServer struct{}

func (UnimplementedConfigSyncServer) Connect(grpc.BidiStreamingServer[Heartbeat, ConfigUpdate]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedConfigSyncServer) mustEmbedUnimplementedConfigSyncServer() {}
func (UnimplementedConfigSyncServer) testEmbeddedByValue()                    {}

// UnsafeConfigSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigSyncServer will
// result in compilation errors.
type UnsafeConfigSyncServer interface {
	mustEmbedUnimplementedConfigSyncServer()
}

func RegisterConfigSyncServer(s grpc.ServiceRegistrar, srv ConfigSyncServer) {
	// If the following call panics, it indicates UnimplementedConfigSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigSync_ServiceDesc, srv)
}

func _ConfigSync_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConfigSyncServer).Connect(&grpc.GenericServerStream[Heartbeat, ConfigUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigSync_ConnectServer = grpc.BidiStreamingServer[Heartbeat, ConfigUpdate]

// ConfigSync_ServiceDesc is the grpc.ServiceDesc for ConfigSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wolink.ConfigSync",
	HandlerType: (*ConfigSyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ConfigSync_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/grpc/proto/config_sync.proto",
}
