// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/grpc/proto/config_sync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigType defines the type of configuration update
type ConfigType int32

const (
	ConfigType_FULL           ConfigType = 0
	ConfigType_JWT_KEY        ConfigType = 1
	ConfigType_PROVIDERS      ConfigType = 2
	ConfigType_MODELS         ConfigType = 3
	ConfigType_SECURITY_RULES ConfigType = 4
	ConfigType_NODE_COMMAND   ConfigType = 5
	ConfigType_USER_QUOTA     ConfigType = 6
	ConfigType_DEPT_QUOTA     ConfigType = 7
)

// Enum value maps for ConfigType.
var (
	ConfigType_name = map[int32]string{
		0: "FULL",
		1: "JWT_KEY",
		2: "PROVIDERS",
		3: "MODELS",
		4: "SECURITY_RULES",
		5: "NODE_COMMAND",
		6: "USER_QUOTA",
		7: "DEPT_QUOTA",
	}
	ConfigType_value = map[string]int32{
		"FULL":           0,
		"JWT_KEY":        1,
		"PROVIDERS":      2,
		"MODELS":         3,
		"SECURITY_RULES": 4,
		"NODE_COMMAND":   5,
		"USER_QUOTA":     6,
		"DEPT_QUOTA":     7,
	}
)

func (x ConfigType) Enum() *ConfigType {
	p := new(ConfigType)
	*p = x
	return p
}

func (x ConfigType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_proto_config_sync_proto_enumTypes[0].Descriptor()
}

func (ConfigType) Type() protoreflect.EnumType {
	return &file_internal_grpc_proto_config_sync_proto_enumTypes[0]
}

func (x ConfigType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigType.Descriptor instead.
func (ConfigType) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_proto_config_sync_proto_rawDescGZIP(), []int{0}
}

// Heartbeat sent from gateway to admin
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ConfigVersion int64                  `protobuf:"varint,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       *NodeMetrics           `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_grpc_proto_config_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_config_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_config_sync_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Heartbeat) GetMetrics() *NodeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// NodeMetrics contains runtime metrics for the gateway node
type NodeMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,2,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	RequestRate   int64                  `protobuf:"varint,3,opt,name=request_rate,json=requestRate,proto3" json:"request_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMetrics) Reset() {
	*x = NodeMetrics{}
	mi := &file_internal_grpc_proto_config_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetrics) ProtoMessage() {}

func (x *NodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_config_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetrics.ProtoReflect.Descriptor instead.
func (*NodeMetrics) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_config_sync_proto_rawDescGZIP(), []int{1}
}

func (x *NodeMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NodeMetrics) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *NodeMetrics) GetRequestRate() int64 {
	if x != nil {
		return x.RequestRate
	}
	return 0
}

// ConfigUpdate pushed from admin to gateway
type ConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type          ConfigType             `protobuf:"varint,2,opt,name=type,proto3,enum=wolink.ConfigType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigUpdate) Reset() {
	*x = ConfigUpdate{}
	mi := &file_internal_grpc_proto_config_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigUpdate) ProtoMessage() {}

func (x *ConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_config_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigUpdate.ProtoReflect.Descriptor instead.
func (*ConfigUpdate) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_config_sync_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigUpdate) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigUpdate) GetType() ConfigType {
	if x != nil {
		return x.Type
	}
	return ConfigType_FULL
}

func (x *ConfigUpdate) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// NodeCommand for admin to control gateway nodes
type NodeCommand struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Command           string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`                                              // "maintenance", "restart", "force_down"
	ConfirmationToken string                 `protobuf:"bytes,2,opt,name=confirmation_token,json=confirmationToken,proto3" json:"confirmation_token,omitempty"` // Required for force_down
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeCommand) Reset() {
	*x = NodeCommand{}
	mi := &file_internal_grpc_proto_config_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCommand) ProtoMessage() {}

func (x *NodeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_config_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCommand.ProtoReflect.Descriptor instead.
func (*NodeCommand) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_config_sync_proto_rawDescGZIP(), []int{3}
}

func (x *NodeCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *NodeCommand) GetConfirmationToken() string {
	if x != nil {
		return x.ConfirmationToken
	}
	return ""
}

var File_internal_grpc_proto_config_sync_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_config_sync_proto_rawDesc = "" +
	"\n" +
	"%internal/grpc/proto/config_sync.proto\x12\x06wolink\"\x98\x01\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\x03R\rconfigVersion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12-\n" +
	"\ametrics\x18\x04 \x01(\v2\x13.wolink.NodeMetricsR\ametrics\"x\n" +
	"\vNodeMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\x02 \x01(\x01R\rmemoryPercent\x12!\n" +
	"\frequest_rate\x18\x03 \x01(\x03R\vrequestRate\"j\n" +
	"\fConfigUpdate\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.wolink.ConfigTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"V\n" +
	"\vNodeCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12-\n" +
	"\x12confirmation_token\x18\x02 \x01(\tR\x11confirmationToken*d\n" +
	"\n" +
	"ConfigType\x12\b\n" +
	"\x04FULL\x10\x00\x12\v\n" +
	"\aJWT_KEY\x10\x01\x12\r\n" +
	"\tPROVIDERS\x10\x02\x12\n" +
	"\n" +
	"\x06MODELS\x10\x03\x12\x12\n" +
	"\x0eSECURITY_RULES\x10\x04\x12\x10\n" +
	"\fNODE_COMMAND\x10\x052D\n" +
	"\n" +
	"ConfigSync\x126\n" +
	"\aConnect\x12\x11.wolink.Heartbeat\x1a\x14.wolink.ConfigUpdate(\x010\x01B!Z\x1fwolink-core/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_config_sync_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_config_sync_proto_rawDescData []byte
)

func file_internal_grpc_proto_config_sync_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_config_sync_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_config_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_config_sync_proto_rawDesc), len(file_internal_grpc_proto_config_sync_proto_rawDesc)))
	})
	return file_internal_grpc_proto_config_sync_proto_rawDescData
}

var file_internal_grpc_proto_config_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpc_proto_config_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_grpc_proto_config_sync_proto_goTypes = []any{
	(ConfigType)(0),      // 0: wolink.ConfigType
	(*Heartbeat)(nil),    // 1: wolink.Heartbeat
	(*NodeMetrics)(nil),  // 2: wolink.NodeMetrics
	(*ConfigUpdate)(nil), // 3: wolink.ConfigUpdate
	(*NodeCommand)(nil),  // 4: wolink.NodeCommand
}
var file_internal_grpc_proto_config_sync_proto_depIdxs = []int32{
	2, // 0: wolink.Heartbeat.metrics:type_name -> wolink.NodeMetrics
	0, // 1: wolink.ConfigUpdate.type:type_name -> wolink.ConfigType
	1, // 2: wolink.ConfigSync.Connect:input_type -> wolink.Heartbeat
	3, // 3: wolink.ConfigSync.Connect:output_type -> wolink.ConfigUpdate
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_config_sync_proto_init() }
func file_internal_grpc_proto_config_sync_proto_init() {
	if File_internal_grpc_proto_config_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_config_sync_proto_rawDesc), len(file_internal_grpc_proto_config_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_config_sync_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_config_sync_proto_depIdxs,
		EnumInfos:         file_internal_grpc_proto_config_sync_proto_enumTypes,
		MessageInfos:      file_internal_grpc_proto_config_sync_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_config_sync_proto = out.File
	file_internal_grpc_proto_config_sync_proto_goTypes = nil
	file_internal_grpc_proto_config_sync_proto_depIdxs = nil
}
