# OCR 模型示例
id: example-ocr
name: Example OCR Model
type: ocr
mode: parsed
route: random
icon_uri: default_icon/ocr.png
description:
  zh: OCR 模型示例
  en: Example OCR Model
default_parameters: []
meta:
  protocol: openai
  capability:
    function_call: false
    input_modal:
      - image
    output_modal:
      - text
conn_config:
  base_url: "http://127.0.0.1:8080"
  api_key: "your-api-key"
  model: "example-ocr-model"
status: 1
