id: GLM-OCR-bf16
name: GLM-OCR-bf16
icon_uri: default_icon/glm.png
icon_url: ""
description:
  zh: GLM OCR 模型
  en: GLM OCR Model
default_parameters: []
meta:
  protocol: openai
  capability:
    function_call: false
    input_modal:
      - image
    output_modal:
      - text
conn_config:
  base_url: "http://127.0.0.1:12345"
  api_key: "lingting"
  model: "GLM-OCR-bf16"
status: 1
