id: Qwen3-Embedding-8B-4bit-DWQ
name: Qwen3-Embedding-8B-4bit-DWQ
description:
  zh-CN: Qwen3 Embedding Model
type: text_embedding
protocol: openai
status: 1
connection:
  base_url: http://localhost:8099
  api_key: ""
  model: Qwen3-Embedding-8B-4bit-DWQ
