id: Qwen3-ASR-1.7B-8bit
name: Qwen3-ASR-1.7B-8bit
icon_uri: default_icon/qwen.png
icon_url: ""
description:
  zh: Qwen3 ASR 模型
  en: Qwen3 ASR Model
default_parameters: []
meta:
  protocol: openai
  capability:
    function_call: false
    input_modal:
      - audio
    output_modal:
      - text
conn_config:
  base_url: "http://localhost:8099"
  api_key: "lingting"
  model: "Qwen3-ASR-1.7B-8bit"
status: 1
