id: qwen-tts
name: qwen-tts
icon_uri: default_icon/qwen.png
icon_url: ""
description:
  zh: Qwen3 TTS 模型
  en: Qwen3 TTS Model
default_parameters: []
meta:
  protocol: openai
  capability:
    function_call: false
    input_modal:
      - text
    output_modal:
      - audio
conn_config:
  base_url: "http://localhost:8099"
  api_key: "lingting"
  model: "Qwen3-TTS-12Hz-1.7B-VoiceDesign-8bit"
status: 1
